### ISSUE TITLE
Suggestion, merge HTML-FormFu-Filter-Demoroniser

### ISSUE THREAD

**Issue by djzort** [FormFu/HTML-FormFu#48]
From http://search.cpan.org/~bricas/HTML-FormFu-Filter-Demoroniser

Although change the name, as there is no need to belittle people who are caught up in a windows world

**Comment by nigelm** [comment]
I see the required module `Text::Demoronise` appears not to exist.

There are a bunch of other references to Demoroni[sz]e - for example in https://metacpan.org/pod/HTML::TextToHTML

Maybe there is a more recent version of the same sort of special character filtering - quotes, pound signs etc?

**Comment by djzort** [comment]
Typo perhaps? its there on cpan and by the same author: http://search.cpan.org/~barbie/Text-Demoroniser-0.07/lib/Text/Demoroniser.pm

**Comment by fireartist** [comment]
Brian (the author of that module) is a co-maintainer, so can roll it in to the core if he wishes. I wouldn't really want to do that without checking with him.
