### ISSUE TITLE
broken NAME sections in POD

### ISSUE THREAD

**Issue by fschlich** [FormFu/HTML-FormFu#60]
I'm getting complaints from Debian's QA tool, lintian, that some modules have a NAME section that only contains the package name but no description (the part after the dash). I believe this is because some modules lack an ABSTRACT comment and thus weaver doesn't know what to do, and in some cases produces POD with two NAME sections even, like for HTML::FormFu::Constraint::JSON (version 2.06)

The affected modules are:

HTML::FormFu::Constants
HTML::FormFu::Constraint::JSON
HTML::FormFu::Deploy
HTML::FormFu::Exception
HTML::FormFu::Exception::Constraint
HTML::FormFu::Exception::Inflator
HTML::FormFu::Exception::Input
HTML::FormFu::Exception::Transformer
HTML::FormFu::Exception::Validator
HTML::FormFu::FakeQuery
HTML::FormFu::I18N
HTML::FormFu::I18N::bg
HTML::FormFu::I18N::cs
HTML::FormFu::I18N::da
HTML::FormFu::I18N::de
HTML::FormFu::I18N::en
HTML::FormFu::I18N::es
HTML::FormFu::I18N::fr
HTML::FormFu::I18N::hu
HTML::FormFu::I18N::it
HTML::FormFu::I18N::ja
HTML::FormFu::I18N::no
HTML::FormFu::I18N::pt_br
HTML::FormFu::I18N::pt_pt
HTML::FormFu::I18N::ro
HTML::FormFu::I18N::ru
HTML::FormFu::I18N::tr
HTML::FormFu::I18N::ua
HTML::FormFu::I18N::zh_cn
HTML::FormFu::Literal
HTML::FormFu::Localize
HTML::FormFu::Manual::Unicode
HTML::FormFu::ObjectUtil
HTML::FormFu::Preload
HTML::FormFu::Role::ContainsElements
HTML::FormFu::Role::ContainsElementsSharedWithField
HTML::FormFu::Role::CreateChildren
HTML::FormFu::Role::CustomRoles
HTML::FormFu::Role::Element::Coercible
HTML::FormFu::Role::Element::FieldMethods
HTML::FormFu::Role::Element::Layout
HTML::FormFu::Role::Element::MultiElement
HTML::FormFu::Role::Element::ProcessOptionsFromModel
HTML::FormFu::Role::Element::SingleValueField
HTML::FormFu::Role::FormAndBlockMethods
HTML::FormFu::Role::FormAndElementMethods
HTML::FormFu::Role::GetProcessors
HTML::FormFu::Role::HasParent
HTML::FormFu::Role::NestedHashUtils
HTML::FormFu::Role::Populate
HTML::FormFu::Role::Render
HTML::FormFu::Util

Please add ABSTRACT comments as appropriate.

**Comment by djzort** [comment]
PR would be gladly welcomed

**Comment by fschlich** [comment]
got dzil set up, will send a PR tonight
